FROM node:18.16.0

RUN mkdir -p /app
WORKDIR /app

COPY package*.json ./

RUN npm ci

ENV SKIP_PREFLIGHT_CHECK=true

COPY . ./

# ARG REACT_APP_ENV
# ARG REACT_APP_USER_TYPE
# ARG REACT_APP_BACKEND_URL

# ENV REACT_APP_ENV $REACT_APP_ENV
# ENV REACT_APP_USER_TYPE $REACT_APP_USER_TYPE
# ENV REACT_APP_BACKEND_URL $REACT_APP_BACKEND_URL

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
