name: SOFTAFRIK

on:
  push:
    branches: [ main ]

jobs:

  docker_build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: 85958/softafrik:latest
          
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ~/
            whoami
            docker-compose -f docker-compose-softafrik.yml stop softafrik
            docker pull 85958/softafrik:latest
            docker-compose -f docker-compose-softafrik.yml up -d
            exit
            
           # slack notification
      # - uses: act10ns/slack@v1
      #   env:
      #     SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
      #   with:
      #     status: ${{ job.status }}
      #     steps: ${{ toJson(steps) }}
      #     channel: '#uba_cav_admin'
      #   if: always()
      